-- ========= ENUMS =========
CREATE TYPE tipo_identificacion AS ENUM (
  'Registro Civil', 
  'Tarjeta de Identidad', 
  'Cédula de Ciudadanía', 
  'Cédula Digital', 
  'Pasaporte', 
  'Cédula de Extranjería', 
  'NIT', 
  'Permiso Especial de Permanencia', 
  'Permiso por Protección Temporal', 
  'Documento Extranjero'
);

-- ========= TABLAS INDEPENDIENTES =========
CREATE TABLE hospitales (
  hospitalid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  direccion TEXT NOT NULL,
  telefono TEXT NOT NULL,
  nit TEXT NOT NULL
);

CREATE TABLE especialidades (
  especialidadid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL
);

CREATE TABLE motivosvisitas (
  motivoid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descripcion TEXT NOT NULL
);

CREATE TABLE medicamentos (
  medicamentoid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  prescripcion TEXT NOT NULL,
  unidades TEXT NOT NULL,
  cantidad BIGINT NOT NULL,
  descripcion TEXT
);

CREATE TABLE pacientes (
  pacienteid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  apellido TEXT NOT NULL,
  fechanacimiento DATE NOT NULL,
  sexo TEXT NOT NULL,
  direccion TEXT NOT NULL,
  telefono TEXT NOT NULL,
  correoelectronico TEXT NOT NULL
);


-- ========= NIVEL 1 DEPENDENCIAS =========
CREATE TABLE medicos (
  medicoid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  apellido TEXT NOT NULL,
  especialidadid BIGINT NOT NULL REFERENCES especialidades(especialidadid) ON DELETE CASCADE,
  hospitalid BIGINT NOT NULL REFERENCES hospitales(hospitalid) ON DELETE CASCADE,
  telefono TEXT NOT NULL,
  correoelectronico TEXT NOT NULL
);


-- ========= NIVEL 2 DEPENDENCIAS =========
CREATE TABLE visitas (
  visitaid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha DATE NOT NULL,
  hora TIME NOT NULL,
  medicoid BIGINT NOT NULL REFERENCES medicos(medicoid) ON DELETE CASCADE,
  pacienteid BIGINT NOT NULL REFERENCES pacientes(pacienteid) ON DELETE CASCADE
);


-- ========= NIVEL 3 DEPENDENCIAS =========
CREATE TABLE signosvitales (
  signovitalid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  visitaid BIGINT NOT NULL REFERENCES visitas(visitaid) ON DELETE CASCADE,
  frecuenciacardiaca BIGINT NOT NULL,
  frecuenciarespiratoria BIGINT NOT NULL,
  presionarterial TEXT NOT NULL,
  saturacionoxigeno BIGINT NOT NULL,
  temperatura NUMERIC NOT NULL
);

CREATE TABLE detallesvisitas (
  detallevisitaid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  visitaid BIGINT NOT NULL REFERENCES visitas(visitaid) ON DELETE CASCADE,
  motivoid BIGINT NOT NULL REFERENCES motivosvisitas(motivoid) ON DELETE CASCADE,
  diagnostico TEXT NOT NULL
);

CREATE TABLE orden_examenes (
  ordenexamenid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  visitaid BIGINT NOT NULL REFERENCES visitas(visitaid) ON DELETE CASCADE,
  fecha DATE NOT NULL
);

CREATE TABLE tratamientos (
  tratamientoid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  visitaid BIGINT NOT NULL REFERENCES visitas(visitaid) ON DELETE CASCADE,
  fechainicio DATE NOT NULL,
  fechafin DATE
);


-- ========= NIVEL 4 DEPENDENCIAS =========
CREATE TABLE detallesexamenes (
  detalleexamenid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ordenexamenid BIGINT NOT NULL REFERENCES orden_examenes(ordenexamenid) ON DELETE CASCADE,
  tipoexamen TEXT NOT NULL,
  nombreexamen TEXT NOT NULL,
  indicaciones TEXT
);

CREATE TABLE formulas (
  formulaid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tratamientoid BIGINT NOT NULL REFERENCES tratamientos(tratamientoid) ON DELETE CASCADE,
  fecha DATE NOT NULL
);

CREATE TABLE incapacidades (
  incapacidadid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tratamientoid BIGINT NOT NULL REFERENCES tratamientos(tratamientoid) ON DELETE CASCADE,
  fecha DATE NOT NULL
);


-- ========= NIVEL 5 DEPENDENCIAS =========
CREATE TABLE detallesformulas (
  detalleid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  formulaid BIGINT NOT NULL REFERENCES formulas(formulaid) ON DELETE CASCADE,
  medicamentoid BIGINT NOT NULL REFERENCES medicamentos(medicamentoid) ON DELETE CASCADE,
  presentacion TEXT NOT NULL,
  posologia TEXT NOT NULL,
  periodicidaduso TEXT NOT NULL,
  periodouso TEXT NOT NULL
);

CREATE TABLE detallesincapacidades (
  detalleid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  incapacidadid BIGINT NOT NULL REFERENCES incapacidades(incapacidadid) ON DELETE CASCADE,
  numerodias BIGINT NOT NULL,
  fechainicio DATE NOT NULL,
  fechafin DATE NOT NULL,
  descripcion TEXT NOT NULL
);
